name: Auto-merge master in master_sf_vs_sf

on:
  push:
    branches:
      - master   # Trigger only when master is updated
  workflow_dispatch: # allows manual triggering

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your branch
        uses: actions/checkout@v4
        with:
          ref: master_sf_vs_sf
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Fetch master
        run: git fetch origin master

      - name: Merge master into branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge master --no-edit

      - name: Push changes to your fork
        run: git push origin master_sf_vs_sf
